### ISSUE TITLE
JAVA warning

### ISSUE THREAD

**Issue by chaelli** [projectestac/jclic#1]
Hi

I started to get the attached error messages. I thought it would help to use the applet directly from here: http://clic.xtec.cat/dist/jclic/ to get the most current version which would solve the problem.. but it didn't...

you can test this on www.below.ch/rump/18630-s-1-3kl-derwildehund/

am I doing something wrong? Can this be solved? do I need to compile the software myself?

Cheers
Michael

![2013-11-19 21_48_07-der wilde hund](https://f.cloud.github.com/assets/878151/1576376/fbed327a-515b-11e3-9dcc-5f6e56ce6377.png)

**Comment by frncesc** [comment]
The JClic applet is signed with an official VeriSign certificate from March 25 2014, so this issue can be closed.
