### ISSUE TITLE
FUNCIONA EL BUSCADOR D'ACTITATS?

### ISSUE THREAD

**Issue by josepvidal** [projectestac/jclic#12]
Hola, ja feia una temporada més o menys llarga que no buscava activitats de jclic. La sorpresa salta quan desde cap ordinador al meu abast (que en son més de 40) es pot accedir al buscador d'activitats. És que li passa alguna cosa al buscador?

PD. M'he cerciorat de fer les coses correctes, actualització de programari, buscar altres buscadors... i perdut en aquest oceà informàtic, no trobe solució.

Gracies, a veure si algú m'ho aclara josepvidalmartin@hotmail.com

**Comment by frncesc** [comment]
Bon dia,

Si et refereixes al buscador d'activitats de la zonaClic (http://clic.xtec.cat/db/listact_ca.jsp), ara mateix està funcionant sense problemes. Tampoc tenim cap incidència reportada en els darrers dies.

Si et dóna algun error, si et plau escriu-nos directament a clic@xtec.cat
