### ISSUE TITLE
HTML5 - No sound with simpleassociation B panel

### ISSUE THREAD

**Issue by Okaryn** [projectestac/jclic#14]
Hi,

When I convert a Jclic in HTML5, I don't have sound with "B" panel in simpleassociation activity.

If I swap A and B panel content, the sound is OK (I swap the primary and secondary tag in the .jclic file)

Try with Chrome/Firefox/IE 11

Thanks !

**Comment by frncesc** [comment]
Issue moved to __jclic.js__: https://github.com/projectestac/jclic.js/issues/3
