### ISSUE TITLE
Jclic stopped working in HTML5

### ISSUE THREAD

**Issue by JesusMey** [projectestac/jclic#17]
The package is created with Jclic , it includes an instruction to load the javascript library that makes the jclic in HTML5

<script type="text/javascript" src="https://cdn.jsdelivr.net/jclic.js/latest/jclic.min.js"></script>

This instruction loads the latest version of this library available (latest ) . That's why that once worked, but there are today no longer ( has since changed )

Information provided by Victor Ponz in http://mestreacasa.gva.es/web/portaleducativo/foro/message_boards/message/500015231948

**Comment by frncesc** [comment]
Hola Jesús,

Ara mateix tenim dos llocs des d'on es distribueix el codi del JClic.js:

https://clic.xtec.cat/dist/jclic.js/jclic.min.js
https://cdn.jsdelivr.net/jclic.js/latest/jclic.min.js

El primer URL s'actualitza amb més freqüència, i ara mateix serveix la versió 0.1.35. En canvi, a jsdelivr.net la branca "latest" té encara la 0.1.34. En aquest cas es poden obtenir també versions anteriors canviant "latest" pel número de versió desitjada (tot i que "latest" sempre hauria de funcionar millor :-)

Pel que estic provant, tant la 0.1.34 com la 35 segueixen funcionant correctament amb un navegador actualitzat. Al repositori principal fem servir la 0.1.35:
http://clic.xtec.cat/repo

... i en aquest espai de proves la 0.1.34 de jsdelivr:
http://clic.xtec.cat/temp/index_bombers.html

Si us plau, passeu-me l'URL del lloc on us estigui fallant i miro què pot ser. Digueu-me també amb quin navegador web ho mireu.

Gràcies!

**Comment by JesusMey** [comment]
Hola

En este blog tengo colgados los JCLIC's. El primero que aparece está en HTML5 y el resto en JAVA

http://mestreacasa.gva.es/web/mey_jes/19

Los navegadores utilizados son Firefox y Chrome, ambos en sistemas Windows y Ubuntu

Gracias

**Comment by frncesc** [comment]
¡Problema localizado y solucionado!

El error se producía al intentar detectar la función SCORM cuando JClic.js corría en un "iFrame" con un origen distinto al de la página principal. En esta situación se producía una infracción de la política [_same-origin_](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) que impedía la ejecución del script principal.

En el caso que comentas, la página principal pertenece a `mestreacasa.gva.es`, pero la aplicación corre en una ventana interna (__iframe__) con contenido de `rec.mestreacasa.gva.es`. El navegador considera que son servidores distintos y eso produce un error que impide cargar las actividades.

El problema está solucionado en la [versión 0.1.35](https://github.com/projectestac/jclic.js/releases/tag/v0.1.35) de JClic.js desde hace unos minutos, pero _JSdelivr_ todavía no suministra la última versión en __"latest"__ debido a que se actualiza en [periodos de 7 días](https://github.com/jsdelivr/jsdelivr/issues/13595).

De momento las opciones que tenéis son:

- Esperar 7 días (o quizás menos) a que JSDelivr actualice el script.

- Descargar la [nueva versión 0.3.2.1 de JClic Author](http://clic.xtec.cat/es/jclic/download.htm), abrir y exportar nuevamente el paquete JClic a HTML5 y volver a subirlo a "mestreacasa". El principal cambio es que ahora el script se descarga directamente de "clic.xtec.cat" (que actualizamos nosotros) en lugar de hacerlo de "cdn.jsdelivr.net" con un retraso de 7 días.

- Presentar a los alumnos un enlace directo a la página con las actividades. Por ejemplo, enlazar directamente a: http://rec.mestreacasa.gva.es/webzip/29747207-0123-4ef1-921d-d2539ef5099a/html5/index.html en página nueva. De esta manera las actividades se abren correctamente.

**Comment by JesusMey** [comment]
Hola

Muchísimas gracias!!

Saludos!

**Comment by frncesc** [comment]
Veo que JSDelivr ya ha actualizado la versión _latest_ de JClic.js. Las actividades incrustadas deberían funcionar ahora correctamente.

De no ser así, por favor reabrid la issue.

Saludos cordiales,

Francesc
