### ISSUE TITLE
Generador automatico de contenido

### ISSUE THREAD

**Issue by JesusMey** [projectestac/jclic#19]
Hola

He realizado un proyecto JCLIC en el que he utilizado el generador automatico de contenidos Arith.

Las actividades funcionan bien el el PC pero cuando exporto el proyecto a HTML5 y lo subo a la web, estas actividades no funcionan correctamente

El proyecto se encuentra en esta web y las actividades son de los tipos: Memory y respuesta escrita

[http://mestreacasa.gva.es/web/mey_jes/28](http://mestreacasa.gva.es/web/mey_jes/28)

**Comment by frncesc** [comment]
Hola,

Creo que se debe al mismo error reportado en:
https://github.com/projectestac/jclic/issues/20

... que ha sido solucionado hoy mismo en:
https://github.com/projectestac/jclic.js/issues/10

La versión corregida será publicada el próximo 2 de noviembre. A partir de este día debería funcionar correctamente. Si no fuera así, avísa y reabrimos la issue.

¡Gracias por reportar errores!
