### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by belekes** [projectestac/jclic#20]
When I generate my exercises tot HTML5 I get this in my browsers: NaN instead of numbers.
See: http://oefenen.blokje.be/jclic/tafelvan1/
In the preview it is looking good.
How can I solve this?
Thanks for your help.
Peter

**Comment by frncesc** [comment]
Issue confirmed and [moved](https://github.com/projectestac/jclic.js/issues/10) to the jclic.js repository.

Thanks for reporting!

**Comment by frncesc** [comment]
Problem [solved in jclic.js](https://github.com/projectestac/jclic.js/issues/10)
The solution will be published in JClic.js V0.1.38, to be released in two days (expected 02/Nov/2016)

Thanks for reporting!
