### ISSUE TITLE
Problemas con JCLIC en WEB

### ISSUE THREAD

**Issue by JesusMey** [projectestac/jclic#22]
Saludos

últimamente he detectado algunos problemas en los proyectos que realizo. Estos problemas tan solo aparecen al exportar el proyecto JCLIC a HTML5 y colgarlo en el blog

1. En la secuencia de actividades elimino los botones de avanzar actividad pero en la versión HTML5 estos botones siempre aparecen en perfecto funcionamiento

2. Hay actividades tipo Texto Rellenar Agujeros que avanzan automáticamente. La actividad en concreto la tengo configurada para que avance a  los 5 segundos cuando esté resuelta de manera correcta, pero avanza a los 5 segundos de iniciarse.

[Imagen](http://mestreacasa.gva.es/documents/4700293490/500015875382/DLFE-1142825.png )

En esta actividad aparece seleccionada por defecto la primera opción. En uno de los casos es correcta, pero no cuenta como tal

Se puede comprobar en el [blog](http://mestreacasa.gva.es/web/mey_jes/25)

Otra cosa que me gustaría que con el tiempo se modificara es el boton de eliminar ectividad en JCLIC AUTHOR. Creo que el botón debería redirigir a una ventana de confirmación. en muchas ocasiones vamos con prisas realizando las actividades y eliminamos alguna sin querer, echando a perder tiempo y esfuerzo

Gracias por todo

Saludos

**Comment by frncesc** [comment]
He dividido el problema en tres issues, dos en JClic.js y otra en JClic:

https://github.com/projectestac/jclic.js/issues/11
https://github.com/projectestac/jclic.js/issues/12
#23
