### ISSUE TITLE
Millores a la traducció en català

### ISSUE THREAD

**Issue by jordimas** [projectestac/jclic#25]
Ep!

Hem afegit el Jclic a les memòries de Softcatalà:https://www.softcatala.org/recursos/memories.html

Com part d'això generem informes d'error automatizats. Veure:

https://www.softcatala.org/recursos/quality/jclic.html

Veureu que hi ha algunes coses a corregir

Salut,

Jordi.

**Comment by frncesc** [comment]
Hem incorporat als fitxers `.po` i `.properties` els suggeriments fets per Softcatalà, excepte alguns falsos positius deguts a l'ús del caràcter "|" (_pipe_) com a separador entre el literal d'acció de menú i la seva descripció, entre altres.

Moltes gràcies Jordi!!
