### ISSUE TITLE
SSL Offload problem

### ISSUE THREAD

**Issue by jsfalcon** [projectestac/jclic#8]
Hi, 

When we work with an ssl offload architecture. where proxy and apache talk on http while clients are talking on https. 
JClic constructs its request on http, but the request must be https to work correctly

This is the var we use for our architecture 
$CFG->sslproxy  = true;
And we define the var $CFG->wwwroot = 'https://.....'

Thansk a lot!

**Comment by frncesc** [comment]
Hi jsfalcon,

The new version of the JClic module for Moodle, just published today, solves this problem:

https://github.com/projectestac/moodle-mod_jclic/releases/tag/v0.2.5
https://moodle.org/plugins/view/mod_jclic

Thanks for reporting!

**Comment by jsfalcon** [comment]
great!
We'll try it as soon as posible
Thanks
